import { Injectable } from '@angular/core';
import {
  Project,
  Table,
  Persona,
  Screen,
  CriticalAction,
  JourneyStep,
  CrudEntity,
  ExternalApi,
  Webhook,
  GlossaryTerm,
} from '../../models';

export interface DocumentationFile {
  filename: string;
  content: string;
}

@Injectable({
  providedIn: 'root',
})
export class DocumentationGeneratorService {
  generateClaudeMd(project: Project, tables: Table[]): string {
    let content = '';

    content += this.generateHeader(project);
    content += this.generateProjectOverview(project);
    content += this.generateUxSection(project);
    content += this.generateRequirementsSection(project);
    content += this.generateDataArchitectureSection(project, tables);
    content += this.generateStackSection(project);
    content += this.generateIntegrationsSection(project);
    content += this.generateEnvironmentsSection(project);
    content += this.generateGlossarySection(project);
    content += this.generateFooter();

    return content;
  }

  generateReadme(project: Project, tables: Table[]): string {
    let content = '';

    content += `# ${project.name}\n\n`;

    if (project.description) {
      content += `${project.description}\n\n`;
    }

    content += `## Quick Start\n\n`;
    content += `\`\`\`bash\n`;
    content += `# Clone the repository\n`;
    content += `git clone <repository-url>\n\n`;
    content += `# Install dependencies\n`;
    content += `composer install\n`;
    content += `npm install\n\n`;
    content += `# Run migrations\n`;
    content += `php artisan migrate\n\n`;
    content += `# Start development server\n`;
    content += `php artisan serve\n`;
    content += `\`\`\`\n\n`;

    content += `## Database\n\n`;
    content += `- **Type:** ${project.databaseType.toUpperCase()}\n`;
    content += `- **Tables:** ${tables.length}\n\n`;

    if (tables.length > 0) {
      content += `### Tables\n\n`;
      tables.forEach((table) => {
        const columnCount = table.columns?.length || 0;
        content += `- \`${table.name}\` - ${columnCount} columns`;
        if (table.description) {
          content += ` - ${table.description}`;
        }
        content += `\n`;
      });
      content += `\n`;
    }

    content += `## Documentation\n\n`;
    content += `- [claude.md](./claude.md) - Complete project documentation for AI assistants\n`;
    content += `- [migrations/](./migrations/) - Laravel migration files\n`;
    content += `- [schema.sql](./schema.sql) - Raw SQL schema\n\n`;

    content += `## License\n\n`;
    content += `This project is proprietary.\n\n`;

    content += `---\n`;
    content += `*Generated by Software Architecture Builder*\n`;

    return content;
  }

  generateAllDocumentation(project: Project, tables: Table[]): DocumentationFile[] {
    return [
      {
        filename: 'claude.md',
        content: this.generateClaudeMd(project, tables),
      },
      {
        filename: 'README.md',
        content: this.generateReadme(project, tables),
      },
    ];
  }

  private generateHeader(project: Project): string {
    const now = new Date().toISOString().split('T')[0];
    let content = `# ${project.name}\n\n`;
    content += `> Documentação gerada automaticamente pelo Software Architecture Builder\n`;
    content += `> Data: ${now}\n\n`;
    return content;
  }

  private generateProjectOverview(project: Project): string {
    let content = `## Visão Geral do Projeto\n\n`;

    if (project.description) {
      content += `${project.description}\n\n`;
    }

    content += `### Configurações Técnicas\n\n`;
    content += `| Configuração | Valor |\n`;
    content += `|--------------|-------|\n`;
    content += `| Banco de Dados | ${project.databaseType.toUpperCase()} |\n`;
    content += `| Charset | ${project.databaseCharset} |\n`;
    content += `| Collation | ${project.databaseCollation} |\n`;
    if (project.tablePrefix) {
      content += `| Prefixo de Tabelas | ${project.tablePrefix} |\n`;
    }
    content += `\n`;

    return content;
  }

  private generateUxSection(project: Project): string {
    const ux = project.uxData;
    if (!ux) return '';

    let content = `## UX Research\n\n`;

    // Personas
    if (ux.personas && ux.personas.length > 0) {
      content += `### Personas\n\n`;
      ux.personas.forEach((persona: Persona) => {
        content += `#### ${persona.isPrimary ? '(Principal) ' : ''}${persona.name}\n\n`;
        content += `- **Faixa etária:** ${persona.ageRange}\n`;
        content += `- **Perfil técnico:** ${persona.technicalProfile}\n`;
        content += `- **Profissão:** ${persona.profession}\n`;
        content += `- **Contexto de uso:** ${persona.usageContext}\n`;
        content += `- **Frustrações:** ${persona.frustrations}\n`;
        content += `- **Objetivos:** ${persona.objectives}\n\n`;
      });
    }

    // Problem Central
    if (ux.problemCentral) {
      const problem = ux.problemCentral;
      content += `### Problema Central\n\n`;
      if (problem.problemStatement) {
        content += `**Problema:** ${problem.problemStatement}\n\n`;
      }
      if (problem.detailedDescription) {
        content += `**Descrição detalhada:** ${problem.detailedDescription}\n\n`;
      }
      if (problem.proposedSolution) {
        content += `**Solução proposta:** ${problem.proposedSolution}\n\n`;
      }
      if (problem.differential) {
        content += `**Diferencial:** ${problem.differential}\n\n`;
      }
    }

    // Journey
    if (ux.journey && ux.journey.length > 0) {
      content += `### Jornada do Usuário\n\n`;
      const sortedJourney = [...ux.journey].sort((a: JourneyStep, b: JourneyStep) => a.order - b.order);
      sortedJourney.forEach((step: JourneyStep) => {
        content += `${step.order}. **${step.title}** - ${step.description}`;
        if (step.emotion) {
          content += ` _(${step.emotion})_`;
        }
        content += `\n`;
      });
      content += `\n`;
    }

    // Screens
    if (ux.screens && ux.screens.length > 0) {
      content += `### Telas Planejadas\n\n`;
      content += `| Tela | Tipo | Prioridade | Descrição |\n`;
      content += `|------|------|------------|------------|\n`;
      ux.screens.forEach((screen: Screen) => {
        content += `| ${screen.name} | ${screen.type} | ${screen.priority} | ${screen.description || '-'} |\n`;
      });
      content += `\n`;
    }

    // Critical Actions
    if (ux.criticalActions && ux.criticalActions.length > 0) {
      content += `### Ações Críticas\n\n`;
      ux.criticalActions.forEach((action: CriticalAction) => {
        const icon = this.getCriticalityIcon(action.criticality);
        content += `- ${icon} **${action.action}** - ${action.description}\n`;
      });
      content += `\n`;
    }

    // Usage Context
    if (ux.usageContext) {
      const ctx = ux.usageContext;
      content += `### Contexto de Uso\n\n`;
      content += `- **Frequência de uso:** ${ctx.frequency}\n`;
      content += `- **Dispositivo prioritário:** ${ctx.priorityDevice}\n`;
      content += `- **Plataformas-alvo:** ${ctx.targetPlatforms?.join(', ') || 'Não definido'}\n`;
      content += `- **Requer offline:** ${ctx.offlineRequired ? 'Sim' : 'Não'}\n`;
      if (ctx.accessibilityRequirements && ctx.accessibilityRequirements.length > 0) {
        content += `- **Acessibilidade:** ${ctx.accessibilityRequirements.join(', ')}\n`;
      }
      content += `\n`;
    }

    return content;
  }

  private generateRequirementsSection(project: Project): string {
    const req = project.requirementsData;
    if (!req) return '';

    let content = `## Requisitos de Software\n\n`;

    // Functional Requirements
    if (req.functional) {
      content += `### Requisitos Funcionais\n\n`;

      // CRUD Entities
      if (req.functional.crudEntities && req.functional.crudEntities.length > 0) {
        content += `#### Entidades CRUD\n\n`;
        content += `| Entidade | Create | List | View | Edit | Delete | Export | Import |\n`;
        content += `|----------|--------|------|------|------|--------|--------|--------|\n`;
        req.functional.crudEntities.forEach((entity: CrudEntity) => {
          const c = entity.create ? 'X' : '-';
          const l = entity.list ? 'X' : '-';
          const v = entity.view ? 'X' : '-';
          const e = entity.edit ? 'X' : '-';
          const d = entity.delete ? 'X' : '-';
          const ex = entity.export ? 'X' : '-';
          const im = entity.import ? 'X' : '-';
          content += `| ${entity.name} | ${c} | ${l} | ${v} | ${e} | ${d} | ${ex} | ${im} |\n`;
        });
        content += `\n`;
      }
    }

    // Moscow Prioritization
    if (req.moscow) {
      content += `### Priorização MoSCoW\n\n`;

      if (req.moscow.mustHave && req.moscow.mustHave.length > 0) {
        content += `#### Must Have\n`;
        req.moscow.mustHave.forEach((item: string) => {
          content += `- ${item}\n`;
        });
        content += `\n`;
      }

      if (req.moscow.shouldHave && req.moscow.shouldHave.length > 0) {
        content += `#### Should Have\n`;
        req.moscow.shouldHave.forEach((item: string) => {
          content += `- ${item}\n`;
        });
        content += `\n`;
      }

      if (req.moscow.couldHave && req.moscow.couldHave.length > 0) {
        content += `#### Could Have\n`;
        req.moscow.couldHave.forEach((item: string) => {
          content += `- ${item}\n`;
        });
        content += `\n`;
      }

      if (req.moscow.wontHave && req.moscow.wontHave.length > 0) {
        content += `#### Won't Have (v1)\n`;
        req.moscow.wontHave.forEach((item: string) => {
          content += `- ${item}\n`;
        });
        content += `\n`;
      }
    }

    return content;
  }

  private generateDataArchitectureSection(project: Project, tables: Table[]): string {
    if (!tables || tables.length === 0) return '';

    let content = `## Arquitetura de Dados\n\n`;
    content += `O projeto possui **${tables.length}** tabela(s) definida(s).\n\n`;

    tables.forEach((table) => {
      content += `### Tabela: ${table.name}\n\n`;

      if (table.description) {
        content += `${table.description}\n\n`;
      }

      const columns = table.columns || [];
      if (columns.length > 0) {
        content += `| Coluna | Tipo | Nullable | Default | Atributos |\n`;
        content += `|--------|------|----------|---------|------------|\n`;

        columns.forEach((col) => {
          const attrs: string[] = [];
          if (col.isPrimaryKey) attrs.push('PK');
          if (col.isForeignKey) attrs.push('FK');
          if (col.isAutoIncrement) attrs.push('AI');
          if (col.isUnique) attrs.push('UQ');
          if (col.isIndexed) attrs.push('IDX');
          if (col.isUnsigned) attrs.push('UNSIGNED');

          let colType = col.dataType;
          if (col.dataLength) colType += `(${col.dataLength})`;
          if (col.dataPrecision && col.dataScale) {
            colType += `(${col.dataPrecision},${col.dataScale})`;
          }

          content += `| ${col.name} | ${colType} | ${col.isNullable ? 'YES' : 'NO'} | ${col.defaultValue || '-'} | ${attrs.join(', ') || '-'} |\n`;
        });
        content += `\n`;

        // Foreign Keys
        const fkColumns = columns.filter((c) => c.isForeignKey && c.foreignKey);
        if (fkColumns.length > 0) {
          content += `**Relacionamentos:**\n`;
          fkColumns.forEach((col) => {
            const fk = col.foreignKey!;
            content += `- \`${col.name}\` → \`${fk.referenceTable}.${fk.referenceColumn}\` (ON DELETE ${fk.onDelete}, ON UPDATE ${fk.onUpdate})\n`;
          });
          content += `\n`;
        }
      }

      // Table options
      const options: string[] = [];
      if (table.hasTimestamps) options.push('timestamps (created_at, updated_at)');
      if (table.hasSoftDelete) options.push('soft delete (deleted_at)');
      if (options.length > 0) {
        content += `*Opções: ${options.join(', ')}*\n\n`;
      }
    });

    return content;
  }

  private generateStackSection(project: Project): string {
    let content = '';

    // Frontend Stack
    if (project.frontendStackData) {
      const fe = project.frontendStackData;
      content += `## Stack Frontend\n\n`;

      if (fe.ionic) content += `- **Ionic:** ${fe.ionic.version}\n`;
      if (fe.angular) {
        content += `- **Angular:** ${fe.angular.version}`;
        if (fe.angular.strictMode) content += ` (strict mode)`;
        if (fe.angular.standaloneComponents) content += ` (standalone)`;
        content += `\n`;
      }
      if (fe.capacitor) {
        content += `- **Capacitor:** ${fe.capacitor.version}`;
        if (fe.capacitor.platforms && fe.capacitor.platforms.length > 0) {
          content += ` (${fe.capacitor.platforms.join(', ')})`;
        }
        content += `\n`;
      }

      if (fe.dependencies && fe.dependencies.length > 0) {
        content += `\n**Dependências principais:**\n`;
        fe.dependencies
          .filter((d) => d.enabled)
          .forEach((dep) => {
            content += `- ${dep.name}${dep.version ? ` @${dep.version}` : ''}${dep.isDev ? ' (dev)' : ''}\n`;
          });
      }
      content += `\n`;
    }

    // Backend Stack
    if (project.backendStackData) {
      const be = project.backendStackData;
      content += `## Stack Backend\n\n`;

      if (be.php) content += `- **PHP:** ${be.php.version}\n`;
      if (be.laravel) {
        content += `- **Laravel:** ${be.laravel.version}`;
        if (be.laravel.starterKit) content += ` (${be.laravel.starterKit})`;
        content += `\n`;
        if (be.laravel.apiAuth) content += `- **API Auth:** ${be.laravel.apiAuth}\n`;
      }
      if (be.database) {
        content += `- **Database Driver:** ${be.database.driver}\n`;
        if (be.database.redis) content += `- **Redis:** Habilitado\n`;
      }

      if (be.packages && be.packages.length > 0) {
        content += `\n**Pacotes principais:**\n`;
        be.packages
          .filter((p) => p.enabled)
          .forEach((pkg) => {
            content += `- ${pkg.name}${pkg.version ? ` @${pkg.version}` : ''}\n`;
          });
      }
      content += `\n`;
    }

    return content;
  }

  private generateIntegrationsSection(project: Project): string {
    const integrations = project.integrationsData;
    if (!integrations) return '';

    let content = '';

    // External APIs
    if (integrations.externalApis && integrations.externalApis.length > 0) {
      content += `## Integrações Externas\n\n`;
      content += `### APIs\n\n`;

      integrations.externalApis.forEach((api: ExternalApi) => {
        content += `#### ${api.name}\n\n`;
        content += `- **Categoria:** ${api.category}\n`;
        content += `- **URL Base:** ${api.baseUrl}\n`;
        content += `- **Versão API:** ${api.apiVersion}\n`;
        content += `- **Autenticação:** ${api.authType}\n`;
        if (api.purpose) content += `- **Propósito:** ${api.purpose}\n`;
        if (api.documentationUrl) content += `- **Documentação:** ${api.documentationUrl}\n`;
        if (api.envVariables && api.envVariables.length > 0) {
          content += `- **Variáveis de ambiente:** \`${api.envVariables.join('`, `')}\`\n`;
        }
        content += `\n`;
      });
    }

    // Webhooks
    const hasWebhooks =
      (integrations.webhooksReceived && integrations.webhooksReceived.length > 0) ||
      (integrations.webhooksSent && integrations.webhooksSent.length > 0);

    if (hasWebhooks) {
      content += `### Webhooks\n\n`;

      if (integrations.webhooksReceived && integrations.webhooksReceived.length > 0) {
        content += `**Recebidos:**\n`;
        integrations.webhooksReceived.forEach((wh: Webhook) => {
          content += `- \`${wh.event}\` de ${wh.source} → ${wh.endpoint}`;
          if (wh.action) content += ` (${wh.action})`;
          content += `\n`;
        });
        content += `\n`;
      }

      if (integrations.webhooksSent && integrations.webhooksSent.length > 0) {
        content += `**Enviados:**\n`;
        integrations.webhooksSent.forEach((wh: Webhook) => {
          content += `- \`${wh.event}\` → ${wh.endpoint}\n`;
        });
        content += `\n`;
      }
    }

    return content;
  }

  private generateEnvironmentsSection(project: Project): string {
    const envs = project.environmentsData;
    if (!envs) return '';

    let content = `## Ambientes\n\n`;

    const envList = [
      { key: 'local', name: 'Local', config: envs.local },
      { key: 'development', name: 'Development', config: envs.development },
      { key: 'staging', name: 'Staging', config: envs.staging },
      { key: 'production', name: 'Production', config: envs.production },
    ];

    envList.forEach((env) => {
      if (env.config && (env.config.frontendUrl || env.config.apiUrl)) {
        content += `### ${env.name}\n\n`;
        if (env.config.frontendUrl) content += `- **Frontend:** ${env.config.frontendUrl}\n`;
        if (env.config.apiUrl) content += `- **API:** ${env.config.apiUrl}\n`;
        if (env.config.adminUrl) content += `- **Admin:** ${env.config.adminUrl}\n`;
        if (env.config.server) content += `- **Server:** ${env.config.server}\n`;
        if (env.config.database) content += `- **Database:** ${env.config.database}\n`;
        if (env.config.notes) content += `- **Notas:** ${env.config.notes}\n`;
        content += `\n`;
      }
    });

    return content;
  }

  private generateGlossarySection(project: Project): string {
    const glossary = project.glossaryData;
    if (!glossary || !glossary.terms || glossary.terms.length === 0) return '';

    let content = `## Glossário\n\n`;

    const sortedTerms = [...glossary.terms].sort((a: GlossaryTerm, b: GlossaryTerm) =>
      a.term.localeCompare(b.term)
    );

    sortedTerms.forEach((term: GlossaryTerm) => {
      content += `### ${term.term}\n\n`;
      content += `${term.definition}\n`;
      if (term.synonyms && term.synonyms.length > 0) {
        content += `\n*Sinônimos: ${term.synonyms.join(', ')}*\n`;
      }
      if (term.usageExample) {
        content += `\n*Exemplo: ${term.usageExample}*\n`;
      }
      content += `\n`;
    });

    return content;
  }

  private generateFooter(): string {
    return `---\n\n*Este documento foi gerado automaticamente pelo Software Architecture Builder.*\n`;
  }

  private getCriticalityIcon(criticality: string): string {
    switch (criticality) {
      case 'blocking':
        return '🔴';
      case 'high':
        return '🟠';
      case 'medium':
        return '🟡';
      case 'low':
        return '🟢';
      default:
        return '⚪';
    }
  }
}
